### ISSUE TITLE
Exception thrown in service call is obscured

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-vm#1012]
### Expected Behavior

If an exception is thrown during a service call (`dispatch.call` or similar), then the promise returned to the caller should get rejected with details of the original exception.

### Actual Behavior

The promise is rejected but the exception information is not copied faithfully. For example, this exception):
```
DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://****' failed to load.
    at .../extension-worker.js:220:21
```
...is reported like this:
```
DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': DOMException object could not be cloned.
    at .../extension-worker.js:721:30
    at new Promise (<anonymous>)
    at WorkerDispatch._remoteTransferCall (.../extension-worker.js:710:20)
    at WorkerDispatch.transferCall (.../extension-worker.js:647:57)
    at WorkerDispatch.call (.../extension-worker.js:614:38)
    at .../extension-worker.js:229:30
```

### Steps to Reproduce

- Load an extension in a worker
- Call a function in the extension which throws an exception
- Examine the rejected promise from the VM (or in the JS debugger)

**Comment by cwillisf** [comment]
This should be a simple fix... it looks like the code is trying to include the exception object where it should stringify or JSON-ify it.

This doesn't have much impact on main-line Scratch 3.0 work right now, since we don't have exceptions in workers, but it might affect those using scratch-vm for other extension development projects. For example, @stefania11 ran into this recently with her work.
