### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#106]
NPM logs:

```
npm http GET https://github.com/LLK/scratch-vm.git
npm http 200 https://github.com/LLK/scratch-vm.git
npm ERR! not a package C:\Users\<profile>\AppData\Local\Temp\npm-5824-AVbExXPz\1471614396399-0.8327982956543565\tmp.tgz
npm ERR! Error: ENOENT: no such file or directory, open 'C:\Users\<profile>\AppData\Roaming\npm-cache\tmp_e419811fe2f2tmp_0728858f6d55package\package.json'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "E:\\node\\node.exe" "E:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/LLK/scratch-vm.git"
npm ERR! cwd E:\node
npm ERR! node -v v4.4.5
npm ERR! npm -v 1.4.9
npm ERR! path C:\Users\<profile>\AppData\Roaming\npm-cache\tmp_e419811fe2f2tmp_0728858f6d55package\package.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\node\npm-debug.log
npm ERR! not ok code 0
```

where `<profile>` is my profile name

**Comment by tmickel** [comment]
@cwillisf Have you seen something like this before?

**Comment by cwillisf** [comment]
Hmm... I haven't seen this myself, no. I just tried installing `scratch-vm` with `npm install` on Windows and it went OK for me in a command prompt, but didn't work correctly in a Cygwin shell. It looks like the error I see in Cygwin could be related to what @dekrain is seeing, but it's not quite the same (see below).

@dekrain, one thing you might try is to clear your NPM cache (in `C:\Users\<profile>\AppData\Roaming\npm-cache\`) in case something got messed up in there. Also, it looks like you're running a much older version of `npm` than the one I have, so it might be worth trying to update `npm` and see if that helps.

Here's what I did to get mine working:

```
md foo
cd foo
npm init -y
npm install --save https://github.com/LLK/scratch-vm.git
```

Versions:

```
D:\foo>git --version
git version 2.8.1.windows.1

D:\foo>npm --version
3.10.6

D:\foo>ver

Microsoft Windows [Version 10.0.14393]
```

Regarding use from Cygwin: it looks like `npm` doesn't work correctly with `git` under Cygwin. There are several active conversations about it over on the `npm` Github repository, such as:
- https://github.com/npm/npm/issues/7357
- https://github.com/npm/npm/issues/7456
- https://github.com/npm/npm/pull/12366

It appears that the short answer is to use `npm` from a Command Prompt window, not from Cygwin. I actually find that I can safely use `npm` from Cygwin as long as `npm` isn't itself using `git`, but strictly speaking I don't think it's officially supported even then.

Some of those discussions on the `npm` repository mention this page, which includes instructions to get `npm` working with Cygwin. I haven't tried this myself, so please be careful if you try: make backups as appropriate, etc.
https://github.com/emigenix/npm_on_cygwin

For the record, here's what I see when I try to install `scratch-vm` from Cygwin. Note that it looks like it's trying to use the directory `/cygdrive/c/Users/<profile>/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-LLK-scratch-vm-git-43980326/C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326` which mixes Cygwin and Windows path conventions and is not a valid path overall.

```
~/foo $ npm install --save https://github.com/LLK/scratch-vm.git
npm ERR! git clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe: Cloning into 'C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe'...
npm ERR! git clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe: fatal: '/cygdrive/c/Users/<profile>/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-LLK-scratch-vm-git-43980326/C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326' does not appear to be a git repository
npm ERR! git clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe:
npm ERR! git clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe: and the repository exists.
npm ERR! git clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\<profile>\\AppData\\Roaming\\nodejs\\node.exe" "C:\\Users\\<profile>\\AppData\\Roaming\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "https://github.com/LLK/scratch-vm.git"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.6
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326 C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe
npm ERR! Cloning into 'C:\cygwin64\tmp\npm-12420-4f2b1acd\git-cache-0c891ea1\852690d7cbe4bcb2428fe212efb1583f9ff612fe'...
npm ERR! fatal: '/cygdrive/c/Users/<profile>/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-LLK-scratch-vm-git-43980326/C:\Users\<profile>\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-vm-git-43980326' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<profile>\foo\npm-debug.log
```

**Comment by dekrain** [comment]
I updated npm and **I added git to %path%**
I got a message:

```
Scratch-VM@1.0.0 E:\Scratch-VM
`-- scratch-vm@0.1.0  (git+https://github.com/LLK/scratch-vm.git#852690d7cbe4bcb2428fe212efb1583f9ff612fe)
  +-- htmlparser2@3.9.0
  | +-- domelementtype@1.3.0
  | +-- domhandler@2.3.0
  | +-- domutils@1.5.1
  | | `-- dom-serializer@0.1.0
  | |   `-- domelementtype@1.1.3
  | +-- entities@1.1.1
  | `-- readable-stream@2.1.5
  |   +-- buffer-shims@1.0.0
  |   +-- core-util-is@1.0.2
  |   +-- inherits@2.0.1
  |   +-- isarray@1.0.0
  |   +-- process-nextick-args@1.0.7
  |   +-- string_decoder@0.10.31
  |   `-- util-deprecate@1.0.2
  `-- memoizee@0.3.10
    +-- d@0.1.1
    +-- es5-ext@0.10.12
    | +-- es6-iterator@2.0.0
    | `-- es6-symbol@3.1.0
    +-- es6-weak-map@0.1.4
    | +-- es6-iterator@0.1.3
    | `-- es6-symbol@2.0.1
    +-- event-emitter@0.3.4
    +-- lru-queue@0.1.0
    +-- next-tick@0.2.2
    `-- timers-ext@0.1.0

npm WARN Scratch-VM@1.0.0 No description
npm WARN Scratch-VM@1.0.0 No repository field.
```

**Comment by dekrain** [comment]
In my directory, only `node_modules` dir and package.json was created
Versions of git and npm was the same like above

**Comment by cwillisf** [comment]
@dekrain good news: it looks like it worked! Check in `node_modules/scratch-vm` and you should see all the `scratch-vm` files. You can also try the instructions from the [README.md](https://github.com/LLK/scratch-vm#readme) to play around with the VM now.

Note that installing `scratch-vm` with `npm install` is best if you'd like to use `scratch-vm` as a part of your own application or library, but forking and then cloning the `scratch-vm` repository with `git clone` may be better if you want to play with or modify `scratch-vm` itself.

**Comment by dekrain** [comment]
When i use `npm install` on downloaded repository, logs:

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  git+https://git@github.com/LLK/scratch-blocks.git resetting remote C:\Users\<prof>\AppData\Roaming\npm-cache\_git-remotes\git-https-git-gi
thub-com-LLK-scratch-blocks-git-91472b17 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

,but with cleaned cache, it crash (nothing do)

**Comment by dekrain** [comment]
Wait, after this message, after waiting a while, finally it worked :smile:
