### ISSUE TITLE
Travis Build Failure - `Error: Cannot find module 'scratch-render/src/index.js'`

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#1237]
Log from build failure:

```
> scratch-vm@0.1.0 build /home/travis/build/LLK/scratch-vm
> webpack --progress --colors --bail

/home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/webpack.js:243
				throw err;
				^

Error: Cannot find module 'scratch-render/src/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.require.resolve (/home/travis/build/LLK/scratch-vm/node_modules/v8-compile-cache/v8-compile-cache.js:162:23)
    at Object.<anonymous> (/home/travis/build/LLK/scratch-vm/webpack.config.js:137:35)
    at Module._compile (/home/travis/build/LLK/scratch-vm/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/travis/build/LLK/scratch-vm/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/webpack.js:240:39)
    at Object.parse (/home/travis/build/LLK/scratch-vm/node_modules/yargs/yargs.js:552:18)
    at /home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/webpack.js:218:8
    at Object.<anonymous> (/home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/LLK/scratch-vm/node_modules/webpack/bin/webpack.js:157:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by kchadha** [comment]
Seen twice now. Once on a pull request (restarting that job fixed the issue), and once on a different pull request merge (where the PR build wasn't failing, but the build for merging that PR into develop did fail).
