### ISSUE TITLE
run  npm start failed

### ISSUE THREAD

**Issue by LCINA** [LLK/scratch-vm#2193]
### Expected Behavior

In `develop` branch.
run `npm start` succeed.

### Actual Behavior

run  `npm start` failed

### Steps to Reproduce

1. run `yarn` or `npm i` shell. Then install succeed.

2. run `npm start` failed. The error message is as follows.

> ERROR in ./src/playground/benchmark.js
    Module not found: Error: Can't resolve 'scratch-svg-renderer' in '/Users/xxx/Desktop/work/code/LLK/scratch-vm/src/playground'
     @ ./src/playground/benchmark.js 109:25-56
    ERROR in [copy-webpack-plugin] unable to locate 'node_modules/scratch-svg-renderer/dist/web' at '/Users/xxx/Desktop/work/code/LLK/scratch-vm/node_modules/scratch-svg-renderer/dist/web'

The `scratch-svg-renderer` package doesn‘t contain `/dist` folder. Then I ran `yarn` and `npm run build` in this package. But build failed. The error message is as follows.

> Module not found: Error: Can't resolve 'scratch-render-fonts/DonegalOne-Regular.ttf' in '/Users/xxx/Desktop/work/code/LLK/scratch-vm/node_modules/_scratch-svg-renderer@0.1.0-prerelease.1515800444@scratch-svg-renderer/src'
    at factoryCallback (/Users/xxx/Desktop/work/code/LLK/scratch-vm/node_modules/_scratch-svg-renderer@0.1.0-prerelease.1515800444@scratch-svg-renderer/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/xxx/Desktop/work/code/LLK/scratch-vm/node_modules/_scratch-svg-renderer@0.1.0-prerelease.1515800444@scratch-svg-renderer/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/Users/xxx/Desktop/work/code/LLK/scratch-vm/node_modules/_scratch-svg-renderer@0.1.0-prerelease.1515800444@scratch-svg-renderer/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
...

Please take a look at this question.

Thanks.

### Operating System and Browser

_e.g. Mac OS 10.14.5 Chrome 74.0.3729.169

**Comment by LCINA** [comment]
I tried to change `"scratch-svg-renderer": "lastest"` to `"scratch-svg-renderer": "0.2.0-prerelease.20190523193400"` in `package.json`, then ran success.
