### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getFastBounds' of undefined

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-vm#578]
### Expected Behavior
https://scratch.mit.edu/projects/156140411/
Project works.

### Actual Behavior
https://llk.github.io/scratch-gui/#156140411
After a few seconds:
Uncaught TypeError: Cannot read property 'getFastBounds' of undefined
    at https://llk.github.io/scratch-gui/gui.js:109072:48
    at Array.filter (native)
    at RenderWebGL._filterCandidatesTouching (https://llk.github.io/scratch-gui/gui.js:109068:41)
    at RenderWebGL.isTouchingDrawables (https://llk.github.io/scratch-gui/gui.js:108802:33)
    at RenderedTarget.isTouchingSprite (https://llk.github.io/scratch-gui/gui.js:10241:34)
    at Scratch3SensingBlocks.touchingObject (https://llk.github.io/scratch-gui/gui.js:19165:32)
    at execute (https://llk.github.io/scratch-gui/gui.js:20068:30)
    at Sequencer.stepThread (https://llk.github.io/scratch-gui/gui.js:21491:17)
    at Sequencer.stepThreads (https://llk.github.io/scratch-gui/gui.js:21446:30)
    at Runtime._step (https://llk.github.io/scratch-gui/gui.js:20833:46)

### Steps to Reproduce

Click https://scratch.mit.edu/projects/156140411/

### Operating System and Browser

OSX 10.11 Chrome 52

**Comment by chrisgarrity** [comment]
@cwillisf any ideas?

**Comment by cwillisf** [comment]
What's happening is that the VM is asking the render if (something) is touching any clone of a particular sprite, but at least one of the clones in the list doesn't have a drawable ID. That could mean that the clone in question has already been deleted but has not been properly cleaned up from the sprite's clone list, or it could mean that the clone in question was just created and doesn't yet have a drawable ID. I suspect it's a cleanup problem but I can't be sure without a more thorough investigation.

**Comment by jwzimmer-zz** [comment]
@cwillisf we also have https://github.com/LLK/scratch-render/issues/78 open, not sure if we want both cases or not?

**Comment by cwillisf** [comment]
Fixed by LLK/scratch-vm#598
